# Generated by Django 3.1.4 on 2020-12-03 07:12

from django.db import migrations, models
import gate_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gate_entry_no', models.CharField(blank=True, default=gate_app.models.increment_invoice_number, max_length=500, null=True)),
                ('Bill_no', models.CharField(max_length=20)),
                ('Vendors', models.CharField(choices=[('G. VIJAY & SONS.', 'G. VIJAY & SONS.'), ('ARKAP KNITS P.LTD.', 'ARKAP KNITS P.LTD.'), ('R.R.ENTERPRISES', 'R.R.ENTERPRISES'), ('Akash Enterprise', 'Akash Enterprise'), ('Naitik Trading Company', 'Naitik Trading Company'), ('Ritesh Knit Fab', 'Ritesh Knit Fab'), ("Knifaso Knit's Fab", "Knifaso Knit's Fab"), ('Netflex (India) Pvt Ltd', 'Netflex (India) Pvt Ltd'), ('Gautam Fabrics', 'Gautam Fabrics'), ('Technocraft Industries India Ltd', 'Technocraft Industries India Ltd'), ('Dilip Fabrics Pvt.Ltd.', 'Dilip Fabrics Pvt.Ltd.'), ('Vastra Creations', 'Vastra Creations'), ('Ampersand', 'Ampersand'), ('Global Touch', 'Global Touch'), ('FRK Textile Screen Printing', 'FRK Textile Screen Printing'), ('RBS Creation', 'RBS Creation'), ('Nalanda Prints', 'Nalanda Prints'), ('JMS Group', 'JMS Group'), ('Om Embroidery', 'Om Embroidery'), ('Dhaga Ghar Threads Pvt Ltd', 'Dhaga Ghar Threads Pvt Ltd'), ('Gaurav Traders', 'Gaurav Traders'), ('R K Global', 'R K Global'), ('Hitesh Treding', 'Hitesh Treding'), ("Shri Sai Knit's", "Shri Sai Knit's"), ('S L Hosiery', 'S L Hosiery'), ('Others', 'others')], max_length=80)),
                ('Inventory_Date', models.DateField(max_length=20)),
                ('Type_of_inward', models.CharField(choices=[('fabric', 'Fabric'), ('print work', 'Print work'), ('accessories', 'Accessories'), ('others', 'Others')], max_length=20)),
                ('Document_Type', models.CharField(choices=[('challan', 'Challan'), ('invoice', 'Invoice')], max_length=20)),
                ('Received_as_QTY', models.CharField(choices=[('KG', 'kg'), ('PIECES', 'pieces'), ('BOX', 'box'), ('Palla', 'palla'), ('Roll', 'roll')], max_length=20)),
                ('Document_QTY', models.CharField(max_length=60)),
                ('Doc_Value', models.CharField(max_length=30)),
                ('Physical_QTY', models.CharField(max_length=60)),
                ('Gate_Enty_Notes', models.CharField(max_length=260)),
                ('Count_Uploades_by', models.CharField(max_length=60)),
                ('upload', models.FileField(null=True, upload_to='')),
                ('Approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], max_length=20)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
