# Generated by Django 3.1.4 on 2020-12-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate_app', '0002_auto_20201209_0737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='headshot',
        ),
        migrations.AddField(
            model_name='invoice',
            name='Upload',
            field=models.ImageField(blank=True, null=True, upload_to='invoice_upload/'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='Vendors',
            field=models.CharField(choices=[('FRK Textile Screen Printing', 'FRK Textile Screen Printing'), ('Dhaga Ghar Threads Pvt Ltd', 'Dhaga Ghar Threads Pvt Ltd'), ('Om Embroidery', 'Om Embroidery'), ('Ocean International', 'Ocean International'), ('Sports Print', 'Sports Print'), ('Ritesh Knit Fab', 'Ritesh Knit Fab'), ('Hitesh Trading', 'Hitesh Trading'), ('Akash Enterprises', 'Akash Enterprises'), ('Gaurav Traders', 'Gaurav Traders'), ('Poonam Enterprises', 'Poonam Enterprises'), ('Maa Textiles', 'Maa Textiles'), ('Heena Arts', 'Heena Arts'), ('Tasa Graphic Prints LLP', 'Tasa Graphic Prints LLP'), ('Vastra Creations', 'Vastra Creations'), ('Global Touch', 'Global Touch'), ('R K Global', 'R K Global'), ('Poonam Enterprises', 'Poonam Enterprises'), ('RBS Creation', 'RBS Creation'), ('Knifaso Knits Fab', 'Knifaso Knits Fab'), ('ASHIRWAD CREATION', 'ASHIRWAD CREATION'), ('Patel Rib', 'Patel Rib'), ('Santosh Kumar Jaiswar', 'Santosh Kumar Jaiswar'), ('Netflex India Pvt Ltd', 'Netflex India Pvt Ltd'), ('High-Touch Services', 'High-Touch Services'), ('Santosh Kumar Thakur', 'Santosh Kumar Thakur'), ('JMS Group', 'JMS Group'), ('G. Vijay & Sons', 'G. Vijay & Sons'), ('Arkap Knits P.Ltd', 'Arkap Knits P.Ltd'), ('SUNART AGENCIES PVTLTD', 'SUNART AGENCIES PVTLTD'), ('INDU ENTERPRISES', 'INDU ENTERPRISES'), ('pramukh print', 'pramukh print'), ('TEJAS ENTERPRISE', 'TEJAS ENTERPRISE'), ('Nalanda Prints', 'Nalanda Prints'), ('Pappu Yadav', 'Pappu Yadav'), ('Ampersand', 'Ampersand'), ('R.R.Enterprises', 'R.R.Enterprises'), ('Shri Sai Knits', 'Shri Sai Knits'), ('Dilip Fabrics PVT LTD', 'Dilip Fabrics PVT LTD'), ('Rita sales agency', 'Rita sales agency'), ('SURAJ PAPER MART', 'SURAJ PAPER MART'), ('Alkemi Decor Designs Pvt Ltd', 'Alkemi Decor Designs Pvt Ltd'), ('Rampstar Clothing', 'Rampstar Clothing'), ('Alok Labels And Tags', 'Alok Labels And Tags'), ('Shivshakti Garments', 'Shivshakti Garments'), ('Gautam Fabrics', 'Gautam Fabrics'), ('S L Hosiery', 'S L Hosiery'), ('Dernier Overseas', 'Dernier Overseas'), ('Manki Art', 'Manki Art'), ('Royal Enterprises', 'Royal Enterprises'), ('Sahara Kaaj Buttons & Tailoring Material', 'Sahara Kaaj Buttons & Tailoring Material'), ('Trendy Incorp', 'Trendy Incorp'), ('Varun Overseas', 'Varun Overseas'), ('Sonal Enterprises', 'Sonal Enterprises'), ('Arihant Packaging', 'Arihant Packaging'), ('Y.S.Apparels', 'Y.S.Apparels'), ('Sahil Prints', 'Sahil Prints'), ('Naitik Trading Co.', 'Naitik Trading Co.'), ('Milan Packaging Solutions', 'Milan Packaging Solutions'), ('Rajshrey Text Pvt Ltd', 'Rajshrey Text Pvt Ltd'), ('Technocraft Industries Ltd', 'Technocraft Industries Ltd'), ('Hallmark Knit Fabrics P LTD', 'Hallmark Knit Fabrics P LTD'), ('J K Digital Prints', 'J K Digital Prints'), ('Others', 'others')], max_length=80),
        ),
    ]
